"""empty message

Revision ID: d4ad03862084
Revises: d2767a3cb105
Create Date: 2020-12-17 20:03:53.517100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4ad03862084'
down_revision = 'd2767a3cb105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.String(), nullable=True),
    sa.Column('height', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('breakfast', sa.String(), nullable=True),
    sa.Column('lunch', sa.String(), nullable=True),
    sa.Column('desert', sa.String(), nullable=True),
    sa.Column('is_publish', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('diet plan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet plan',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"diet plan_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('weight', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('height', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('breakfast', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lunch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('desert', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_publish', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='diet plan_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='diet plan_pkey')
    )
    op.drop_table('schedule')
    # ### end Alembic commands ###
